services:
  db:
    image: mongo:8.2.5
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./service/backend
    container_name: backend_app
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017
    depends_on:
      - db

  frontend:
    build:
      context: ./service/frontend
      args:
        - VITE_API_BASE=/api
        - VITE_API_URL=http://backend:8000
    container_name: frontend_app
    restart: always
    ports:
      - "127.0.0.1:5173:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mongo_data: